[global]
direct=1
thread=1
norandommap=1
randrepeat=1
runtime=30
ramp_time=3
numjobs=8

filename=/dev/md5
ioengine=libaio
bs=64k
iodepth=32

[write-seq]
wait_for_previous
group_reporting
rw=randwrite
